/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.pkg.perpustakaangamplong;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author milstrike
 */

public class Operator extends javax.swing.JFrame {

    /**
     * Creates new form Operator
     */
    public dbAccess db = new dbAccess();
    public mainFunction mf = new mainFunction();
    public Operator() {
        initComponents();
        initLevel0();
        initLevel1();
        changeAllBlack();
        initLevel2();
        initLevel3();
        initLevel4();
        initLevel5();
        initLevel6();
        panelBeranda.setVisible(true);
        
    }
    
    public void initLevel0(){
        this.setExtendedState(this.getExtendedState() | JFrame.MAXIMIZED_BOTH);
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon-apps-16.png")));
    }
    
    public void initLevel1(){
        berandaMenu.setHorizontalTextPosition(javax.swing.JLabel.CENTER);
        berandaMenu.setVerticalTextPosition(javax.swing.JLabel.BOTTOM);
        berandaMenu.setText("   Beranda   ");
        
        sirkulasiMenu.setHorizontalTextPosition(javax.swing.JLabel.CENTER);
        sirkulasiMenu.setVerticalTextPosition(javax.swing.JLabel.BOTTOM);
        sirkulasiMenu.setText("   Sirkulasi   ");
        
        katalogMenu.setHorizontalTextPosition(javax.swing.JLabel.CENTER);
        katalogMenu.setVerticalTextPosition(javax.swing.JLabel.BOTTOM);
        katalogMenu.setText("   Katalog   ");
        
        keanggotaanMenu.setHorizontalTextPosition(javax.swing.JLabel.CENTER);
        keanggotaanMenu.setVerticalTextPosition(javax.swing.JLabel.BOTTOM);
        keanggotaanMenu.setText("   Keanggotaan   ");
        
    }
    
    public void initLevel2(){
        berandaMenu.setForeground(Color.ORANGE);
    }
    
    public void initLevel3(){
        panelBeranda.setVisible(false);
        panelSirkulasi.setVisible(false);
        panelKatalogGeneral.setVisible(false);
        panelKeanggotaan.setVisible(false);
    }
    
    public void initLevel4(){
        addWindowListener(new java.awt.event.WindowAdapter() {
    @Override
    public void windowClosing(java.awt.event.WindowEvent windowEvent) {
        if (JOptionPane.showConfirmDialog(null, 
            "Apakah Anda ingin keluar dari Aplikasi?", "Konfirmasi keluar?", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            System.exit(0);
            }
    }
        });
    }
    
    public void initLevel5(){
        db.showPengaturanDenda();
        db.showDaftarSirkulasi();
        db.showKatalog();
        db.showKeanggotaan();
    }
    
    public void initLevel6(){
        globalVariabel.editData = 0;
        globalVariabel.cekData = 0;
        globalVariabel.cekDataKeanggotaan = 0;
        globalVariabel.changePassword = 0;
        globalVariabel.editKatalog = 0;
        globalVariabel.editUser = 0;
        globalVariabel.passwordEditor = 0;
        globalVariabel.cekPengembalian = 0;
        
        checkBebasDenda.setEnabled(false);
        cekData.setSelected(false);
        aktivasiEdit.setSelected(false);
        
        btnPinjamanKembali.setEnabled(false);
        
        textStatusKeterlambatan.setText("-");
        textDenda.setText("-");
    }
    
    public void exitApplication(){
        if (JOptionPane.showConfirmDialog(null, 
            "Apakah Anda ingin keluar dari Aplikasi?", "Konfirmasi keluar?", 
            JOptionPane.YES_NO_OPTION,
            JOptionPane.QUESTION_MESSAGE) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }
    
    public void changeAllBlack(){
        berandaMenu.setForeground(Color.BLACK);
        sirkulasiMenu.setForeground(Color.BLACK);
        katalogMenu.setForeground(Color.BLACK);
        keanggotaanMenu.setForeground(Color.BLACK);    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        berandaMenu = new javax.swing.JLabel();
        sirkulasiMenu = new javax.swing.JLabel();
        katalogMenu = new javax.swing.JLabel();
        keanggotaanMenu = new javax.swing.JLabel();
        generalPanel = new javax.swing.JPanel();
        panelBeranda = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        panelSirkulasi = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        optionPencarianSirkulasi = new javax.swing.JComboBox<>();
        inputPencarianSirkulasi = new javax.swing.JTextField();
        btnPencarianSirkulasi = new javax.swing.JButton();
        btnResetTabelSirkulasi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelSirkulasi = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        inputIDAnggota = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        inputNamaAngfota = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        btnCariAnggota = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelJudulBuku = new javax.swing.JTable();
        btnTambahJudul = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        inputTanggalPinjam = new javax.swing.JTextField();
        btnSetTanggal = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        inputTanggalKembali = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        textStatusKeterlambatan = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        textDenda = new javax.swing.JLabel();
        checkBebasDenda = new javax.swing.JCheckBox();
        btnPinjamanKembali = new javax.swing.JButton();
        btnKonfirmasiPeminjaman = new javax.swing.JButton();
        btnHapusJudul = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        panelKatalogGeneral = new javax.swing.JPanel();
        optionPencarianKatalog = new javax.swing.JComboBox<>();
        inputPencarianKatalog = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelKatalog = new javax.swing.JTable();
        btnPencarianKatalog = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jTabbedPane3 = new javax.swing.JTabbedPane();
        jPanel11 = new javax.swing.JPanel();
        jLabel47 = new javax.swing.JLabel();
        editIDKatalog = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        editJudulKatalog = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        editPengarangKatalog = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        editPenerbitKatalog = new javax.swing.JTextField();
        jLabel51 = new javax.swing.JLabel();
        editISBNKatalog = new javax.swing.JTextField();
        jLabel52 = new javax.swing.JLabel();
        editStokKatalog = new javax.swing.JTextField();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        editLokasiRakKatalog = new javax.swing.JTextField();
        btnResetTabel = new javax.swing.JButton();
        panelKeanggotaan = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tabelAnggota = new javax.swing.JTable();
        optionPencarianAnggota = new javax.swing.JComboBox<>();
        inputPencarianAnggota = new javax.swing.JTextField();
        btnPencarianAnggota = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel6 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        editID = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        editNama = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        editAlamat = new javax.swing.JTextArea();
        jLabel24 = new javax.swing.JLabel();
        editTelepon = new javax.swing.JTextField();
        jLabel25 = new javax.swing.JLabel();
        editTanggal = new javax.swing.JTextField();
        aktivasiEdit = new javax.swing.JCheckBox();
        simpanPerubahanBtn = new javax.swing.JButton();
        btnHapusKeanggotaan = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        newID = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        newNama = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        newAlamat = new javax.swing.JTextArea();
        jLabel29 = new javax.swing.JLabel();
        newTelepon = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        newTanggal = new javax.swing.JTextField();
        tambahAnggotaBtn = new javax.swing.JButton();
        hasilkanIDBtn = new javax.swing.JButton();
        hasilkanTanggalBtn = new javax.swing.JButton();
        cekData = new javax.swing.JCheckBox();
        btnResetTabelKeanggotaan = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        konfigurasiMenu = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        exitMenu = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuBantuan = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuTentang = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Aplikasi Perpustakaan Taman Bacaan Mentari Gamplong III - Operator");
        setResizable(false);

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        berandaMenu.setForeground(new java.awt.Color(204, 153, 0));
        berandaMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/pkg/perpustakaangamplong/home.png"))); // NOI18N
        berandaMenu.setToolTipText("Beranda");
        berandaMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        berandaMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                berandaMenuMouseClicked(evt);
            }
        });
        jToolBar1.add(berandaMenu);

        sirkulasiMenu.setForeground(new java.awt.Color(51, 51, 51));
        sirkulasiMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/pkg/perpustakaangamplong/sirkulasi.png"))); // NOI18N
        sirkulasiMenu.setToolTipText("Manajemen Sirkulasi Perpustakaan");
        sirkulasiMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sirkulasiMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                sirkulasiMenuMouseClicked(evt);
            }
        });
        jToolBar1.add(sirkulasiMenu);

        katalogMenu.setForeground(new java.awt.Color(51, 51, 51));
        katalogMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/pkg/perpustakaangamplong/katalog.png"))); // NOI18N
        katalogMenu.setToolTipText("Lihat dan Cari Katalog");
        katalogMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        katalogMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                katalogMenuMouseClicked(evt);
            }
        });
        jToolBar1.add(katalogMenu);

        keanggotaanMenu.setForeground(new java.awt.Color(51, 51, 51));
        keanggotaanMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/pkg/perpustakaangamplong/keanggotan.png"))); // NOI18N
        keanggotaanMenu.setToolTipText("Manajemen Keanggotaan Perpustakaan");
        keanggotaanMenu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        keanggotaanMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                keanggotaanMenuMouseClicked(evt);
            }
        });
        jToolBar1.add(keanggotaanMenu);

        generalPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Selamat Datang di Aplikasi Perpustakaan Taman Bacaan Mentari Gamplong III");

        jLabel2.setText("Anda login sebagai Administrator");

        jLabel3.setText("Untuk bantuan menggunakan aplikasi ini, Anda dapat menggunakan menu bantuan atau klik bantuan di bawah ini.");

        jLabel4.setForeground(new java.awt.Color(51, 51, 255));
        jLabel4.setText("<html><u>bantuan</u></html>");
        jLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout panelBerandaLayout = new javax.swing.GroupLayout(panelBeranda);
        panelBeranda.setLayout(panelBerandaLayout);
        panelBerandaLayout.setHorizontalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBerandaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(492, Short.MAX_VALUE))
        );
        panelBerandaLayout.setVerticalGroup(
            panelBerandaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBerandaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(564, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        optionPencarianSirkulasi.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        optionPencarianSirkulasi.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Anggota", "Tanggal Pinjam" }));

        btnPencarianSirkulasi.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnPencarianSirkulasi.setText("Cari!");
        btnPencarianSirkulasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPencarianSirkulasiActionPerformed(evt);
            }
        });

        btnResetTabelSirkulasi.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnResetTabelSirkulasi.setText("Reset Tabel");
        btnResetTabelSirkulasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetTabelSirkulasiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(optionPencarianSirkulasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(inputPencarianSirkulasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnPencarianSirkulasi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnResetTabelSirkulasi)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionPencarianSirkulasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPencarianSirkulasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPencarianSirkulasi)
                    .addComponent(btnResetTabelSirkulasi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane1.setForeground(new java.awt.Color(204, 204, 204));

        tabelSirkulasi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "ID Sirkulasi", "ID Anggota", "Nama", "Total Judul", "Tanggal Pinjam", "Tanggal Kembali", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelSirkulasi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelSirkulasiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelSirkulasi);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 847, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("ID Anggota");

        jLabel6.setText("Nama");

        inputNamaAngfota.setEditable(false);

        btnCariAnggota.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnCariAnggota.setText("Cari");
        btnCariAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariAnggotaActionPerformed(evt);
            }
        });

        jScrollPane2.setForeground(new java.awt.Color(204, 204, 204));

        tabelJudulBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "#", "ID Katalog", "Judul Buku"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelJudulBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelJudulBukuMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabelJudulBuku);

        btnTambahJudul.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnTambahJudul.setText("+");
        btnTambahJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahJudulActionPerformed(evt);
            }
        });

        jLabel7.setText("Tanggal Pinjam");

        btnSetTanggal.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnSetTanggal.setText("Set Tanggal");
        btnSetTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSetTanggalActionPerformed(evt);
            }
        });

        jLabel8.setText("Tanggal Kembali");

        jLabel9.setText("Status");

        textStatusKeterlambatan.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        textStatusKeterlambatan.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textStatusKeterlambatan.setText("-");

        jLabel11.setText("Denda");

        textDenda.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        textDenda.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        textDenda.setText("-");

        checkBebasDenda.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        checkBebasDenda.setText("Bebas Denda");
        checkBebasDenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkBebasDendaActionPerformed(evt);
            }
        });

        btnPinjamanKembali.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnPinjamanKembali.setText("Pinjaman Kembali");
        btnPinjamanKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinjamanKembaliActionPerformed(evt);
            }
        });

        btnKonfirmasiPeminjaman.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnKonfirmasiPeminjaman.setText("Konfirmasi Peminjaman");
        btnKonfirmasiPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKonfirmasiPeminjamanActionPerformed(evt);
            }
        });

        btnHapusJudul.setText("-");
        btnHapusJudul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusJudulMouseClicked(evt);
            }
        });

        btnRefresh.setText("Refresh");
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(inputNamaAngfota)
                    .addComponent(jSeparator3)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(inputIDAnggota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCariAnggota))
                    .addComponent(jSeparator4)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textDenda))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(textStatusKeterlambatan))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(btnHapusJudul)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTambahJudul))
                            .addComponent(btnKonfirmasiPeminjaman, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(85, 85, 85)
                                .addComponent(btnSetTanggal))
                            .addComponent(checkBebasDenda))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputTanggalPinjam)
                            .addComponent(inputTanggalKembali, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(102, 102, 102))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addComponent(btnRefresh)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPinjamanKembali)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(0, 0, 0)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputIDAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariAnggota))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(0, 0, 0)
                .addComponent(inputNamaAngfota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahJudul)
                    .addComponent(btnHapusJudul))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addGap(4, 4, 4)
                .addComponent(inputTanggalPinjam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(btnSetTanggal))
                .addGap(4, 4, 4)
                .addComponent(inputTanggalKembali, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnKonfirmasiPeminjaman)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textStatusKeterlambatan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textDenda))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBebasDenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnPinjamanKembali)
                    .addComponent(btnRefresh))
                .addContainerGap())
        );

        javax.swing.GroupLayout panelSirkulasiLayout = new javax.swing.GroupLayout(panelSirkulasi);
        panelSirkulasi.setLayout(panelSirkulasiLayout);
        panelSirkulasiLayout.setHorizontalGroup(
            panelSirkulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1166, Short.MAX_VALUE)
            .addGroup(panelSirkulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSirkulasiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelSirkulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)))
        );
        panelSirkulasiLayout.setVerticalGroup(
            panelSirkulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 597, Short.MAX_VALUE)
            .addGroup(panelSirkulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(panelSirkulasiLayout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(panelSirkulasiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(panelSirkulasiLayout.createSequentialGroup()
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addContainerGap()))
        );

        optionPencarianKatalog.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        optionPencarianKatalog.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Katalog", "Judul Buku", "Pengarang", "ISBN" }));

        tabelKatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "#", "ID Katalog", "Judul", "Pengarang", "Penerbit", "ISBN", "Stok", "Rak"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelKatalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKatalogMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tabelKatalog);

        btnPencarianKatalog.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnPencarianKatalog.setText("Cari");
        btnPencarianKatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPencarianKatalogActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel47.setText("ID Katalog");

        editIDKatalog.setEditable(false);

        jLabel48.setText("Judul");

        editJudulKatalog.setEditable(false);

        jLabel49.setText("Pengarang");

        editPengarangKatalog.setEditable(false);

        jLabel50.setText("Penerbit");

        editPenerbitKatalog.setEditable(false);

        jLabel51.setText("ISBN");

        editISBNKatalog.setEditable(false);

        jLabel52.setText("Stok");

        editStokKatalog.setEditable(false);

        jLabel53.setText("unit");

        jLabel54.setText("Lokasi Rak");

        editLokasiRakKatalog.setEditable(false);

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editIDKatalog)
                    .addComponent(editJudulKatalog)
                    .addComponent(editPengarangKatalog)
                    .addComponent(editPenerbitKatalog)
                    .addComponent(editISBNKatalog)
                    .addComponent(editLokasiRakKatalog)
                    .addGroup(jPanel11Layout.createSequentialGroup()
                        .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47)
                            .addComponent(jLabel48)
                            .addComponent(jLabel49)
                            .addComponent(jLabel50)
                            .addComponent(jLabel51)
                            .addComponent(jLabel52)
                            .addGroup(jPanel11Layout.createSequentialGroup()
                                .addComponent(editStokKatalog, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel53))
                            .addComponent(jLabel54))
                        .addGap(0, 196, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel47)
                .addGap(0, 0, 0)
                .addComponent(editIDKatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel48)
                .addGap(0, 0, 0)
                .addComponent(editJudulKatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel49)
                .addGap(0, 0, 0)
                .addComponent(editPengarangKatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel50)
                .addGap(0, 0, 0)
                .addComponent(editPenerbitKatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel51)
                .addGap(0, 0, 0)
                .addComponent(editISBNKatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel52)
                .addGap(0, 0, 0)
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editStokKatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel53))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel54)
                .addGap(0, 0, 0)
                .addComponent(editLokasiRakKatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(258, Short.MAX_VALUE))
        );

        jTabbedPane3.addTab("Detail Katalog", jPanel11);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 348, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel5Layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 468, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        btnResetTabel.setText("Reset Tabel");
        btnResetTabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetTabelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKatalogGeneralLayout = new javax.swing.GroupLayout(panelKatalogGeneral);
        panelKatalogGeneral.setLayout(panelKatalogGeneralLayout);
        panelKatalogGeneralLayout.setHorizontalGroup(
            panelKatalogGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKatalogGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKatalogGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKatalogGeneralLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 802, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKatalogGeneralLayout.createSequentialGroup()
                        .addComponent(optionPencarianKatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPencarianKatalog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPencarianKatalog)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetTabel)))
                .addContainerGap())
        );
        panelKatalogGeneralLayout.setVerticalGroup(
            panelKatalogGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKatalogGeneralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKatalogGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionPencarianKatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPencarianKatalog, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPencarianKatalog)
                    .addComponent(btnResetTabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelKatalogGeneralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 622, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        tabelAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "#", "ID Anggota", "Nama"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelAnggotaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tabelAnggota);

        optionPencarianAnggota.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        optionPencarianAnggota.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Anggota", "Nama" }));

        btnPencarianAnggota.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnPencarianAnggota.setText("Cari");
        btnPencarianAnggota.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPencarianAnggotaActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel21.setText("ID Anggota");

        editID.setEditable(false);

        jLabel22.setText("Nama");

        editNama.setEditable(false);

        jLabel23.setText("Alamat");

        editAlamat.setEditable(false);
        editAlamat.setColumns(20);
        editAlamat.setRows(5);
        jScrollPane5.setViewportView(editAlamat);

        jLabel24.setText("No Telp / HP");

        editTelepon.setEditable(false);

        jLabel25.setText("Aktif Sejak Tanggal");

        editTanggal.setEditable(false);

        aktivasiEdit.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        aktivasiEdit.setText("Aktifkan Fitur Pengeditan");
        aktivasiEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aktivasiEditActionPerformed(evt);
            }
        });

        simpanPerubahanBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        simpanPerubahanBtn.setText("Simpan Perubahan");
        simpanPerubahanBtn.setEnabled(false);
        simpanPerubahanBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpanPerubahanBtnActionPerformed(evt);
            }
        });

        btnHapusKeanggotaan.setText("Hapus Data");
        btnHapusKeanggotaan.setEnabled(false);
        btnHapusKeanggotaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusKeanggotaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(editID)
                    .addComponent(editNama)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)
                    .addComponent(editTelepon)
                    .addComponent(editTanggal)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22)
                            .addComponent(jLabel23)
                            .addComponent(jLabel24)
                            .addComponent(jLabel25))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(aktivasiEdit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                        .addComponent(btnHapusKeanggotaan)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(simpanPerubahanBtn)))
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(aktivasiEdit)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 205, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(simpanPerubahanBtn)
                    .addComponent(btnHapusKeanggotaan))
                .addContainerGap())
        );

        jTabbedPane1.addTab("  Edit Data  ", jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel26.setText("ID Anggota");

        newID.setEditable(false);

        jLabel27.setText("Nama");

        jLabel28.setText("Alamat");

        newAlamat.setColumns(20);
        newAlamat.setRows(5);
        jScrollPane6.setViewportView(newAlamat);

        jLabel29.setText("No Telp / HP");

        jLabel30.setText("Aktif Sejak Tanggal");

        newTanggal.setEditable(false);

        tambahAnggotaBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        tambahAnggotaBtn.setText("Tambah Anggota");
        tambahAnggotaBtn.setEnabled(false);
        tambahAnggotaBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahAnggotaBtnActionPerformed(evt);
            }
        });

        hasilkanIDBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        hasilkanIDBtn.setText("Hasilkan");
        hasilkanIDBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilkanIDBtnActionPerformed(evt);
            }
        });

        hasilkanTanggalBtn.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        hasilkanTanggalBtn.setText("Hasilkan");
        hasilkanTanggalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hasilkanTanggalBtnActionPerformed(evt);
            }
        });

        cekData.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        cekData.setText("Data sudah diperiksa dan dinyatakan benar");
        cekData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cekDataActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newNama)
                            .addComponent(jScrollPane6)
                            .addComponent(newTelepon)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(tambahAnggotaBtn))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                                .addComponent(newID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(hasilkanIDBtn)))
                        .addContainerGap())
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(newTanggal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(hasilkanTanggalBtn))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel26)
                            .addComponent(jLabel27)
                            .addComponent(jLabel28)
                            .addComponent(jLabel29)
                            .addComponent(jLabel30)
                            .addComponent(cekData))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasilkanIDBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newTelepon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel30)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hasilkanTanggalBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cekData)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(tambahAnggotaBtn)
                .addContainerGap())
        );

        jTabbedPane1.addTab("  Tambah Data  ", jPanel7);

        btnResetTabelKeanggotaan.setText("Reset Tabel");
        btnResetTabelKeanggotaan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetTabelKeanggotaanActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelKeanggotaanLayout = new javax.swing.GroupLayout(panelKeanggotaan);
        panelKeanggotaan.setLayout(panelKeanggotaanLayout);
        panelKeanggotaanLayout.setHorizontalGroup(
            panelKeanggotaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKeanggotaanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKeanggotaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelKeanggotaanLayout.createSequentialGroup()
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 832, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelKeanggotaanLayout.createSequentialGroup()
                        .addComponent(optionPencarianAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputPencarianAnggota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPencarianAnggota)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnResetTabelKeanggotaan)))
                .addContainerGap())
        );
        panelKeanggotaanLayout.setVerticalGroup(
            panelKeanggotaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelKeanggotaanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelKeanggotaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionPencarianAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputPencarianAnggota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnPencarianAnggota)
                    .addComponent(btnResetTabelKeanggotaan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelKeanggotaanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTabbedPane1)
                    .addComponent(jScrollPane4))
                .addContainerGap())
        );

        javax.swing.GroupLayout generalPanelLayout = new javax.swing.GroupLayout(generalPanel);
        generalPanel.setLayout(generalPanelLayout);
        generalPanelLayout.setHorizontalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(generalPanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(panelSirkulasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(generalPanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(panelKatalogGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(generalPanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(panelKeanggotaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );
        generalPanelLayout.setVerticalGroup(
            generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(generalPanelLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(panelBeranda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
            .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(generalPanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(panelSirkulasi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(generalPanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(panelKatalogGeneral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
            .addGroup(generalPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(generalPanelLayout.createSequentialGroup()
                    .addGap(0, 0, 0)
                    .addComponent(panelKeanggotaan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(0, 0, 0)))
        );

        jMenu1.setText("Aplikasi");

        konfigurasiMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/pkg/perpustakaangamplong/user.png"))); // NOI18N
        konfigurasiMenu.setText("Konfigurasi Akun          ");
        konfigurasiMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                konfigurasiMenuActionPerformed(evt);
            }
        });
        jMenu1.add(konfigurasiMenu);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/pkg/perpustakaangamplong/lock.png"))); // NOI18N
        jMenuItem2.setText("Log out dari Aplikasi          ");
        jMenuItem2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuItem2MouseClicked(evt);
            }
        });
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);
        jMenu1.add(jSeparator2);

        exitMenu.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F4, java.awt.event.InputEvent.ALT_MASK));
        exitMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/pkg/perpustakaangamplong/Badge-multiply.png"))); // NOI18N
        exitMenu.setText("Tutup Aplikasi");
        exitMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuActionPerformed(evt);
            }
        });
        jMenu1.add(exitMenu);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Bantuan");

        menuBantuan.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        menuBantuan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/pkg/perpustakaangamplong/help.png"))); // NOI18N
        menuBantuan.setText("Bantuan               ");
        menuBantuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuBantuanActionPerformed(evt);
            }
        });
        jMenu2.add(menuBantuan);
        jMenu2.add(jSeparator1);

        menuTentang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/lib/pkg/perpustakaangamplong/info.png"))); // NOI18N
        menuTentang.setText("Tentang");
        menuTentang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuTentangActionPerformed(evt);
            }
        });
        jMenu2.add(menuTentang);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(generalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(generalPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void konfigurasiMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_konfigurasiMenuActionPerformed
        new pengaturanAkun().setVisible(true);
    }//GEN-LAST:event_konfigurasiMenuActionPerformed

    private void jMenuItem2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuItem2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem2MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        new loginAplikasi().setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void exitMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuActionPerformed
        exitApplication();
    }//GEN-LAST:event_exitMenuActionPerformed

    private void menuBantuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBantuanActionPerformed
        new Bantuan().setVisible(true);
    }//GEN-LAST:event_menuBantuanActionPerformed

    private void menuTentangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTentangActionPerformed
        new About().setVisible(true);
    }//GEN-LAST:event_menuTentangActionPerformed

    private void berandaMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_berandaMenuMouseClicked
        initLevel6();
        changeAllBlack();
        berandaMenu.setForeground(Color.ORANGE);
        initLevel3();
        panelBeranda.setVisible(true);
    }//GEN-LAST:event_berandaMenuMouseClicked

    private void sirkulasiMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_sirkulasiMenuMouseClicked
        initLevel6();
        changeAllBlack();
        sirkulasiMenu.setForeground(Color.ORANGE);
        initLevel3();
        panelSirkulasi.setVisible(true);
    }//GEN-LAST:event_sirkulasiMenuMouseClicked

    private void katalogMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_katalogMenuMouseClicked
        initLevel6();
        changeAllBlack();
        katalogMenu.setForeground(Color.ORANGE);
        initLevel3();
        panelKatalogGeneral.setVisible(true);
    }//GEN-LAST:event_katalogMenuMouseClicked

    private void keanggotaanMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_keanggotaanMenuMouseClicked
        initLevel6();
        changeAllBlack();
        keanggotaanMenu.setForeground(Color.ORANGE);
        initLevel3();
        panelKeanggotaan.setVisible(true);
    }//GEN-LAST:event_keanggotaanMenuMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        new Bantuan().setVisible(true);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void btnPencarianSirkulasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPencarianSirkulasiActionPerformed
        mf.storeSearchOption(optionPencarianSirkulasi.getSelectedItem().toString());
        mf.storeSearchQuery(inputPencarianSirkulasi.getText());
        db.showSirkulasiSearch();
    }//GEN-LAST:event_btnPencarianSirkulasiActionPerformed

    private void btnResetTabelSirkulasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetTabelSirkulasiActionPerformed
        db.showDaftarSirkulasi();
    }//GEN-LAST:event_btnResetTabelSirkulasiActionPerformed

    private void tabelSirkulasiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelSirkulasiMouseClicked
        globalVariabel.IDSirkulasi = tabelSirkulasi.getValueAt(tabelSirkulasi.getSelectedRow(), 1).toString();
        db.selectDataSirkulasi();
        btnKonfirmasiPeminjaman.setEnabled(false);
        btnTambahJudul.setEnabled(false);
        btnHapusJudul.setEnabled(false);
        btnSetTanggal.setEnabled(false);
        btnPinjamanKembali.setRequestFocusEnabled(true);
        mf.hitungTanggalPengembalian();
    }//GEN-LAST:event_tabelSirkulasiMouseClicked

    private void btnCariAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariAnggotaActionPerformed
        String IDAnggota = inputIDAnggota.getText();
        mf.storeIDUserSearch(IDAnggota);
        db.searchIDAnggota();
    }//GEN-LAST:event_btnCariAnggotaActionPerformed

    private void tabelJudulBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelJudulBukuMouseClicked
        String IDKatalog = tabelJudulBuku.getValueAt(tabelJudulBuku.getSelectedRow(), 1).toString();
        mf.storeSelectedDaftarJudul(IDKatalog);
    }//GEN-LAST:event_tabelJudulBukuMouseClicked

    private void btnTambahJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahJudulActionPerformed
        new tambahJudulBuku().setVisible(true);
    }//GEN-LAST:event_btnTambahJudulActionPerformed

    private void btnSetTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSetTanggalActionPerformed
        inputTanggalPinjam.setText(new GeneralConfiguration().getDate());
        inputTanggalKembali.setText(new GeneralConfiguration().getReturnDate());
    }//GEN-LAST:event_btnSetTanggalActionPerformed

    private void checkBebasDendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkBebasDendaActionPerformed
        if(globalVariabel.cekPengembalian == 0){
            btnPinjamanKembali.setEnabled(true);
            globalVariabel.cekPengembalian = 1;
        }
        else{
            btnPinjamanKembali.setEnabled(false);
            globalVariabel.cekPengembalian = 0;
        }
    }//GEN-LAST:event_checkBebasDendaActionPerformed

    private void btnPinjamanKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinjamanKembaliActionPerformed
        db.createLaporanDenda();
        db.updateSirkulasi();
        inputIDAnggota.setText("");
        inputNamaAngfota.setText("");
        inputTanggalPinjam.setText("");
        inputTanggalKembali.setText("");
        btnKonfirmasiPeminjaman.setEnabled(true);
        btnTambahJudul.setEnabled(true);
        btnHapusJudul.setEnabled(true);
        btnSetTanggal.setEnabled(true);
        btnPinjamanKembali.setRequestFocusEnabled(false);
        DefaultTableModel tabelKatalog = (DefaultTableModel) Administrator.tabelJudulBuku.getModel();
        int rowCount = tabelKatalog.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            tabelKatalog.removeRow(i);
        }
        initLevel6();
    }//GEN-LAST:event_btnPinjamanKembaliActionPerformed

    private void btnKonfirmasiPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKonfirmasiPeminjamanActionPerformed
        String IDSirkulasi = new GeneralConfiguration().IDCreator();
        String IDAnggota = inputIDAnggota.getText();
        String TanggalPinjam = inputTanggalPinjam.getText();
        String TanggalKembali = inputTanggalKembali.getText();
        mf.storeSirkulasi(IDSirkulasi, IDAnggota, TanggalPinjam, TanggalKembali);
        int totalData = tabelJudulBuku.getRowCount();
        for(int i=0; i<totalData; i++){
            db.createDetailSirkulasi(tabelJudulBuku.getValueAt(i, 1).toString());
        }
        db.clearJudulBuku();
        db.createDataSirkulasi();
        inputIDAnggota.setText("");
        inputNamaAngfota.setText("");
        inputTanggalPinjam.setText("");
        inputTanggalKembali.setText("");
    }//GEN-LAST:event_btnKonfirmasiPeminjamanActionPerformed

    private void btnHapusJudulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusJudulMouseClicked
        db.deleteJudulBuku();
    }//GEN-LAST:event_btnHapusJudulMouseClicked

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        inputIDAnggota.setText("");
        inputNamaAngfota.setText("");
        inputTanggalPinjam.setText("");
        inputTanggalKembali.setText("");
        btnKonfirmasiPeminjaman.setEnabled(true);
        btnTambahJudul.setEnabled(true);
        btnHapusJudul.setEnabled(true);
        btnSetTanggal.setEnabled(true);
        btnPinjamanKembali.setRequestFocusEnabled(false);
        DefaultTableModel tabelKatalog = (DefaultTableModel) Administrator.tabelJudulBuku.getModel();
        int rowCount = tabelKatalog.getRowCount();
        //Remove rows one by one from the end of the table
        for (int i = rowCount - 1; i >= 0; i--) {
            tabelKatalog.removeRow(i);
        }
        initLevel6();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void tabelKatalogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKatalogMouseClicked
        String IDKatalog = tabelKatalog.getValueAt(tabelKatalog.getSelectedRow(), 1).toString();
        mf.storeSelectedKatalog(IDKatalog);
        db.selectKatalog();
    }//GEN-LAST:event_tabelKatalogMouseClicked

    private void btnPencarianKatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPencarianKatalogActionPerformed
        mf.storeSearchOption(optionPencarianKatalog.getSelectedItem().toString());
        mf.storeSearchQuery(inputPencarianKatalog.getText());
        db.showKatalogSearch();
    }//GEN-LAST:event_btnPencarianKatalogActionPerformed

    private void btnResetTabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetTabelActionPerformed
        db.showKatalog();
    }//GEN-LAST:event_btnResetTabelActionPerformed

    private void tabelAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelAnggotaMouseClicked
        String IDAnggota = tabelAnggota.getValueAt(tabelAnggota.getSelectedRow(), 1).toString();
        mf.storeSelectedKeanggotaan(IDAnggota);
        db.selectKeanggotaan();
        btnHapusKeanggotaan.setEnabled(true);
    }//GEN-LAST:event_tabelAnggotaMouseClicked

    private void btnPencarianAnggotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPencarianAnggotaActionPerformed
        mf.storeSearchOption(optionPencarianAnggota.getSelectedItem().toString());
        mf.storeSearchQuery(inputPencarianAnggota.getText());
        db.showKeanggotaanSearch();
    }//GEN-LAST:event_btnPencarianAnggotaActionPerformed

    private void aktivasiEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aktivasiEditActionPerformed
        if(globalVariabel.editData == 0){
            editNama.setEditable(true);
            editAlamat.setEditable(true);
            editTelepon.setEditable(true);
            simpanPerubahanBtn.setEnabled(true);
            globalVariabel.editData = 1;
        }
        else{
            editNama.setEditable(false);
            editAlamat.setEditable(false);
            editTelepon.setEditable(false);
            simpanPerubahanBtn.setEnabled(false);
            globalVariabel.editData = 0;
        }
    }//GEN-LAST:event_aktivasiEditActionPerformed

    private void simpanPerubahanBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpanPerubahanBtnActionPerformed
        String ID = editID.getText();
        String Nama = editNama.getText();
        String Alamat = editAlamat.getText();
        String Telepon = editTelepon.getText();
        String Tanggal = editTanggal.getText();
        mf.storeKeanggotaan(ID, Nama, Alamat, Telepon, Tanggal);
        db.updateKeanggotaan();
        editID.setText("");
        editNama.setText("");
        editAlamat.setText("");
        editTelepon.setText("");
        editTanggal.setText("");
        editID.setEditable(false);
        editNama.setEditable(false);
        editAlamat.setEditable(false);
        editTelepon.setEditable(false);
        editTanggal.setEditable(false);
        initLevel6();
        aktivasiEdit.setSelected(false);
        simpanPerubahanBtn.setEnabled(true);
    }//GEN-LAST:event_simpanPerubahanBtnActionPerformed

    private void btnHapusKeanggotaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusKeanggotaanActionPerformed
        db.deleteKeanggotaan();
        editID.setText("");
        editNama.setText("");
        editAlamat.setText("");
        editTelepon.setText("");
        editTanggal.setText("");
        editID.setEditable(false);
        editNama.setEditable(false);
        editAlamat.setEditable(false);
        editTelepon.setEditable(false);
        editTanggal.setEditable(false);
    }//GEN-LAST:event_btnHapusKeanggotaanActionPerformed

    private void tambahAnggotaBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahAnggotaBtnActionPerformed
        String ID = newID.getText();
        String Nama = newNama.getText();
        String Alamat = newAlamat.getText();
        String Telepon = newTelepon.getText();
        String Tanggal = newTanggal.getText();
        mf.storeKeanggotaan(ID, Nama, Alamat, Telepon, Tanggal);
        db.createKeanggotaan();
        newID.setText("");
        newNama.setText("");
        newAlamat.setText("");
        newTelepon.setText("");
        newTanggal.setText("");
        initLevel6();
        cekData.setSelected(false);
        tambahAnggotaBtn.setEnabled(true);
    }//GEN-LAST:event_tambahAnggotaBtnActionPerformed

    private void hasilkanIDBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilkanIDBtnActionPerformed
        newID.setText(new GeneralConfiguration().IDUserCreator().toString());
    }//GEN-LAST:event_hasilkanIDBtnActionPerformed

    private void hasilkanTanggalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hasilkanTanggalBtnActionPerformed
        newTanggal.setText(new GeneralConfiguration().getDate().toString());
    }//GEN-LAST:event_hasilkanTanggalBtnActionPerformed

    private void cekDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cekDataActionPerformed
        if(globalVariabel.cekDataKeanggotaan == 0){
            tambahAnggotaBtn.setEnabled(true);
            globalVariabel.cekDataKeanggotaan = 1;
        }
        else{
            tambahAnggotaBtn.setEnabled(false);
            globalVariabel.cekDataKeanggotaan = 0;
        }
    }//GEN-LAST:event_cekDataActionPerformed

    private void btnResetTabelKeanggotaanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetTabelKeanggotaanActionPerformed
        db.showKeanggotaan();
    }//GEN-LAST:event_btnResetTabelKeanggotaanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (globalVariabel.activeTheme.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Operator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Operator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JCheckBox aktivasiEdit;
    private javax.swing.JLabel berandaMenu;
    public static javax.swing.JButton btnCariAnggota;
    public static javax.swing.JButton btnHapusJudul;
    public static javax.swing.JButton btnHapusKeanggotaan;
    public static javax.swing.JButton btnKonfirmasiPeminjaman;
    public static javax.swing.JButton btnPencarianAnggota;
    public static javax.swing.JButton btnPencarianKatalog;
    public static javax.swing.JButton btnPencarianSirkulasi;
    public static javax.swing.JButton btnPinjamanKembali;
    public static javax.swing.JButton btnRefresh;
    public static javax.swing.JButton btnResetTabel;
    public static javax.swing.JButton btnResetTabelKeanggotaan;
    public static javax.swing.JButton btnResetTabelSirkulasi;
    public static javax.swing.JButton btnSetTanggal;
    public static javax.swing.JButton btnTambahJudul;
    public static javax.swing.JCheckBox cekData;
    public static javax.swing.JCheckBox checkBebasDenda;
    public static javax.swing.JTextArea editAlamat;
    public static javax.swing.JTextField editID;
    public static javax.swing.JTextField editIDKatalog;
    public static javax.swing.JTextField editISBNKatalog;
    public static javax.swing.JTextField editJudulKatalog;
    public static javax.swing.JTextField editLokasiRakKatalog;
    public static javax.swing.JTextField editNama;
    public static javax.swing.JTextField editPenerbitKatalog;
    public static javax.swing.JTextField editPengarangKatalog;
    public static javax.swing.JTextField editStokKatalog;
    public static javax.swing.JTextField editTanggal;
    public static javax.swing.JTextField editTelepon;
    private javax.swing.JMenuItem exitMenu;
    private javax.swing.JPanel generalPanel;
    public static javax.swing.JButton hasilkanIDBtn;
    private javax.swing.JButton hasilkanTanggalBtn;
    public static javax.swing.JTextField inputIDAnggota;
    public static javax.swing.JTextField inputNamaAngfota;
    public static javax.swing.JTextField inputPencarianAnggota;
    public static javax.swing.JTextField inputPencarianKatalog;
    public static javax.swing.JTextField inputPencarianSirkulasi;
    public static javax.swing.JTextField inputTanggalKembali;
    public static javax.swing.JTextField inputTanggalPinjam;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel katalogMenu;
    private javax.swing.JLabel keanggotaanMenu;
    private javax.swing.JMenuItem konfigurasiMenu;
    private javax.swing.JMenuItem menuBantuan;
    private javax.swing.JMenuItem menuTentang;
    public static javax.swing.JTextArea newAlamat;
    public static javax.swing.JTextField newID;
    public static javax.swing.JTextField newNama;
    public static javax.swing.JTextField newTanggal;
    public static javax.swing.JTextField newTelepon;
    public static javax.swing.JComboBox<String> optionPencarianAnggota;
    public static javax.swing.JComboBox<String> optionPencarianKatalog;
    public static javax.swing.JComboBox<String> optionPencarianSirkulasi;
    private javax.swing.JPanel panelBeranda;
    private javax.swing.JPanel panelKatalogGeneral;
    private javax.swing.JPanel panelKeanggotaan;
    private javax.swing.JPanel panelSirkulasi;
    public static javax.swing.JButton simpanPerubahanBtn;
    private javax.swing.JLabel sirkulasiMenu;
    public static javax.swing.JTable tabelAnggota;
    public static javax.swing.JTable tabelJudulBuku;
    public static javax.swing.JTable tabelKatalog;
    public static javax.swing.JTable tabelSirkulasi;
    public static javax.swing.JButton tambahAnggotaBtn;
    public static javax.swing.JLabel textDenda;
    public static javax.swing.JLabel textStatusKeterlambatan;
    // End of variables declaration//GEN-END:variables
}
