/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.pkg.perpustakaangamplong;

import java.awt.Color;


/**
 *
 * @author milstrike
 */
public class pengaturanAkun extends javax.swing.JFrame {

    /**
     * Creates new form pengaturanAkun
     */
    public dbAccess db = new dbAccess();
    public pengaturanAkun() {
        initComponents();
        initLevel0();
        initLevel1();
    }
    
    public void initLevel0(){
        setLocationRelativeTo(null);
    }
    
    public void initLevel1(){
        viewNama.setText(globalVariabel.ProfilName);
        viewID.setText(globalVariabel.IDUser);
        viewUsername.setText(globalVariabel.usernameAuth);
        passwordError.setVisible(false);
        passwordError.setForeground(Color.red);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        viewNama = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        viewID = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        viewUsername = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnSimpanPerubahan = new javax.swing.JButton();
        changePassword = new javax.swing.JCheckBox();
        viewPassword1 = new javax.swing.JPasswordField();
        viewPassword2 = new javax.swing.JPasswordField();
        passwordError = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Konfigurasi Akun");
        setType(java.awt.Window.Type.UTILITY);

        jLabel1.setText("Nama");

        jLabel2.setText("ID User");

        viewID.setEditable(false);

        jLabel3.setText("Username");

        viewUsername.setEditable(false);

        jLabel4.setText("Password");

        jLabel5.setText("Re-type Password");

        btnSimpanPerubahan.setText("Simpan Perubahan");
        btnSimpanPerubahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanPerubahanActionPerformed(evt);
            }
        });

        changePassword.setText("Ubah Password");
        changePassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                changePasswordActionPerformed(evt);
            }
        });

        viewPassword1.setEditable(false);

        viewPassword2.setEditable(false);

        passwordError.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        passwordError.setForeground(new java.awt.Color(153, 0, 0));
        passwordError.setText("Password tidak sama!");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpanPerubahan, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(changePassword)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel3)
                                .addComponent(jLabel2)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4))
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(viewPassword2)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(viewNama)
                                    .addComponent(viewUsername)
                                    .addComponent(viewID, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                                    .addComponent(viewPassword1))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(passwordError, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(viewNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(viewID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(viewUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(viewPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(viewPassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passwordError)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addComponent(changePassword)
                .addGap(2, 2, 2)
                .addComponent(btnSimpanPerubahan)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void changePasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_changePasswordActionPerformed
        if(globalVariabel.passwordEditor == 0){
            viewPassword1.setEditable(true);
            viewPassword2.setEditable(true);
            globalVariabel.passwordEditor = 1;
        }
        else{
            viewPassword1.setEditable(false);
            viewPassword2.setEditable(false);
            globalVariabel.passwordEditor = 0;
        }
    }//GEN-LAST:event_changePasswordActionPerformed

    private void btnSimpanPerubahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanPerubahanActionPerformed
        globalVariabel.changeName = viewNama.getText();
        if(globalVariabel.passwordEditor == 1){
            String password1 = new String(viewPassword1.getPassword());
            String password2 = new String(viewPassword2.getPassword());
        if(password1.equalsIgnoreCase("") | password2.equalsIgnoreCase("")){
            passwordError.setVisible(true);
            passwordError.setText("Form password tidak boleh kosong");
            passwordError.setForeground(Color.red);
        }
        else if(password1.equalsIgnoreCase(password2)){
            globalVariabel.changePass = password1;
            db.updateDataSelfUserWithPassword();
        } else {
            passwordError.setVisible(true);
            passwordError.setText("Password tidak sama!");
            passwordError.setForeground(Color.red);
        }
        }
        else{
            db.updateDataSelfUserWithoutPassword();
        }
        viewNama.setText(globalVariabel.ProfilName);
        globalVariabel.passwordEditor = 0;
    }//GEN-LAST:event_btnSimpanPerubahanActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (globalVariabel.activeTheme.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pengaturanAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pengaturanAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pengaturanAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pengaturanAkun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pengaturanAkun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpanPerubahan;
    private javax.swing.JCheckBox changePassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JLabel passwordError;
    public static javax.swing.JTextField viewID;
    public static javax.swing.JTextField viewNama;
    private javax.swing.JPasswordField viewPassword1;
    private javax.swing.JPasswordField viewPassword2;
    public static javax.swing.JTextField viewUsername;
    // End of variables declaration//GEN-END:variables
}
