/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lib.pkg.perpustakaangamplong;

import javax.swing.JOptionPane;
import static lib.pkg.perpustakaangamplong.Administrator.inputPencarianKatalog;
import static lib.pkg.perpustakaangamplong.Administrator.optionPencarianKatalog;

/**
 *
 * @author milstrike
 */
public class tambahJudulBuku extends javax.swing.JFrame {

    /**
     * Creates new form tambahJudulBuku
     */
    
    public dbAccess db = new dbAccess();
    public mainFunction mf = new mainFunction();
    public tambahJudulBuku() {
        initComponents();
        //initLevel0();
        initLevel1();
    }
    
    public void initLevel0(){
        setLocationRelativeTo(null);
    }
    
    public void initLevel1(){
        db.showKatalogTambahBuku();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        optionPencarian = new javax.swing.JComboBox<>();
        inputKataKunci = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelKatalog = new javax.swing.JTable();
        btnTutup = new javax.swing.JButton();
        btnTambahkanKeDaftar = new javax.swing.JButton();
        resetTabelKatalog = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Judul Buku");
        setAlwaysOnTop(true);
        setType(java.awt.Window.Type.UTILITY);

        optionPencarian.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID Katalog", "Judul Buku" }));

        btnCari.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tabelKatalog.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "#", "ID Katalog", "Judul Buku", "Pengarang", "Stok"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelKatalog.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelKatalogMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelKatalog);

        btnTutup.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnTutup.setText("Tutup");
        btnTutup.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTutupActionPerformed(evt);
            }
        });

        btnTambahkanKeDaftar.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        btnTambahkanKeDaftar.setText("Tambahkan ke Daftar");
        btnTambahkanKeDaftar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahkanKeDaftarActionPerformed(evt);
            }
        });

        resetTabelKatalog.setText("Reset Tabel");
        resetTabelKatalog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetTabelKatalogActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 593, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(optionPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(inputKataKunci)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(resetTabelKatalog))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnTutup)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTambahkanKeDaftar)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(optionPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputKataKunci, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari)
                    .addComponent(resetTabelKatalog))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambahkanKeDaftar)
                    .addComponent(btnTutup))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTutupActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTutupActionPerformed
        dispose();
    }//GEN-LAST:event_btnTutupActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        mf.storeSearchOption(optionPencarian.getSelectedItem().toString());
        mf.storeSearchQuery(inputKataKunci.getText());
        db.showKatalogSearchTambahJudulBuku();
    }//GEN-LAST:event_btnCariActionPerformed

    private void resetTabelKatalogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetTabelKatalogActionPerformed
        db.showKatalogTambahBuku();
    }//GEN-LAST:event_resetTabelKatalogActionPerformed

    private void tabelKatalogMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelKatalogMouseClicked
        String IDKatalog = tabelKatalog.getValueAt(tabelKatalog.getSelectedRow(), 1).toString();
        String JudulKatalog = tabelKatalog.getValueAt(tabelKatalog.getSelectedRow(), 2).toString();
        mf.storeSelectedJudulBuku(IDKatalog, JudulKatalog);
    }//GEN-LAST:event_tabelKatalogMouseClicked

    private void btnTambahkanKeDaftarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahkanKeDaftarActionPerformed
        int jumlahBuku = db.getTotalDaftarJudulBuku();
        int maksJumlahBuku = Integer.parseInt(globalVariabel.jumlahJudulMaksimal);
        if(jumlahBuku < maksJumlahBuku){
            db.tambahJudulBuku();
        }
        else{
            JOptionPane.showMessageDialog(null, "Sudah mencapai batas maksimal judul yang diizinkan.");
        }
        
    }//GEN-LAST:event_btnTambahkanKeDaftarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if (globalVariabel.activeTheme.equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tambahJudulBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tambahJudulBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tambahJudulBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tambahJudulBuku.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tambahJudulBuku().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton btnCari;
    public static javax.swing.JButton btnTambahkanKeDaftar;
    public static javax.swing.JButton btnTutup;
    public static javax.swing.JTextField inputKataKunci;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JComboBox<String> optionPencarian;
    public static javax.swing.JButton resetTabelKatalog;
    public static javax.swing.JTable tabelKatalog;
    // End of variables declaration//GEN-END:variables
}
